global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # RAG Platform Services
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8000']
    metrics_path: /metrics
    scrape_interval: 15s

  - job_name: 'document-processor'
    static_configs:
      - targets: ['document-processor:8001']
    metrics_path: /metrics
    scrape_interval: 15s

  - job_name: 'query-intelligence'
    static_configs:
      - targets: ['query-intelligence:8002']
    metrics_path: /metrics
    scrape_interval: 15s

  - job_name: 'vector-search'
    static_configs:
      - targets: ['vector-search:8003']
    metrics_path: /metrics
    scrape_interval: 15s

  - job_name: 'observability'
    static_configs:
      - targets: ['observability:9091']
    metrics_path: /metrics
    scrape_interval: 10s

  # Infrastructure Services
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  - job_name: 'chromadb'
    static_configs:
      - targets: ['chromadb:8000']
    metrics_path: /metrics

  # Node Exporter (if added)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']